fos_rest:
    view:
        formats:
            json: true
        view_response_listener: force
    format_listener:
        default_priorities: ['json', html, '*/*']
        fallback_format: json
    routing_loader:
        default_format: json

twig:
    exception_controller: 'FOS\RestBundle\Controller\ExceptionController::showAction'
    
sensio_framework_extra:
    view:    { annotations: false }
    router:  { annotations: true }