parameters:
    mopa_remote_update_service.class: Mopa\Bundle\RemoteUpdateBundle\Model\RemoteUpdateService
    mopa_local_update_service.class: Mopa\Bundle\RemoteUpdateBundle\Model\LocalUpdateService

services:
    mopa_remote_update_buzz_client:
        class: %buzz.client.class%
        calls:
            - [ setTimeout, [ 360 ] ]
            - [ setMaxRedirects, [ 0 ] ]
    
    mopa_remote_update_wsse_buzz:
        class:     %buzz.browser.class%
        arguments: [@mopa_remote_update_buzz_client, @buzz.message_factory]
        calls:
            - [ addListener, [ @mopa_wsse_authentication.buzz.listener ] ]

    mopa_remote_update_service:
        class:     %mopa_remote_update_service.class%
        arguments: [@service_container, @mopa_remote_update_wsse_buzz, @router]

    mopa_local_update_service:
        class:     %mopa_local_update_service.class%
        arguments: [@service_container]
        