<?php

namespace Mopa\Bundle\RemoteUpdateBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * UpdateJobRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UpdateJobRepository extends EntityRepository
{
}